version: "3.9"

services:

  app:
    build: .
    restart: always
    container_name: App_v2
    depends_on:
      - db
    volumes:
      - ./app:/code/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    networks:
      dbconnection:
        ipv4_address: 10.5.0.5

  db:
    image: postgres:15-alpine
    restart: always
    container_name: PostgreSQL_v15
    volumes:
       - ./dataDB/Volumen:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=passwordRoot
      - POSTGRES_DB=fedeganDB
    networks:
      dbconnection:
        ipv4_address: 10.5.0.6
  
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      dbconnection:
        ipv4_address: 10.5.0.7


networks:
  dbconnection:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1