INSERT INTO Parametros (idParametro,NombreParametro,Valor,idPadre,Descripcion) VALUES 
 (1,'Indice costos produccion',1,null,'Indices de costos de produccion'),
 (2,'Indice Costo Leche',1,1,null),
 (3,'Indice Costo Doble Proposito',2,1,null),
 (4,'Indice Costo Ceba',3,1,null),
 (5,'Indice Costo Cria',4,1,null),
 (6,'Indice Precio Leche',5,1,null),
 (7,'Indice Precio Novillo Gordo',6,1,null),
 (8,'Indice Precio Ganado Flaco',7,1,null),
 (9,'IPC Total',8,1,null),
 (10,'IPC Alimentos',9,1,null),
 (11,'Litro leche pagado al productor',2,null,'Precios por litro de leche pagado al productor'),
 (12,'con bonificaciones voluntarias',1,2,null),
 (13,'sin bonificaciones voluntarias',2,2,null),
 (14,'Bolsa mercantil',3,null,'Precios ganado gordo bolsa mercantil de colombia'),
 (15,'Nacional',1,3,null),
 (16,'Antioquia',2,3,null),
 (17,'Valle del Cauca',3,3,null),
 (18,'Bogota',4,3,null),
 (19,'Santander',5,3,null),
 (20,'Cordoba',6,3,null),
 (21,'Caqueta',7,3,null),
 (22,'Caldas',8,3,null),
 (23,'Atlantico',9,3,null),
 (24,'Cesar',10,3,null),
 (25,'Origen comparativo precio',4,null,'Origenes comparativo precio novillo gordo'),
 (26,'Bolsa Mercantil de Colombia',1,4,null),
 (27,'Promedio subastas ganaderas',2,4,null),
 (28,'Paises novillo gordo',5,null,'Lista paises con precio novillo gordo en pie'),
 (29,'Argentina',1,5,null),
 (30,'Australia',2,5,null),
 (31,'Brasil',3,5,null),
 (32,'Canada',4,5,null),
 (33,'Chile',5,5,null),
 (34,'Colombia',6,5,null),
 (35,'Costa Rica',7,5,null),
 (36,'Ecuador',8,5,null),
 (37,'Estados Unidos',9,5,null),
 (38,'Mexico',10,5,null),
 (39,'Paraguay',11,5,null),
 (40,'Uruguay',12,5,null),
 (41,'Venezuela',13,5,null);
