on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: CI/CD
jobs:
  testing-python:
    name: Running tests
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout Repository
      uses: actions/checkout@master
    - 
      name: Running docker container
      run: |
        sudo docker-compose build
        sudo docker-compose up -d
        sudo docker ps
    -
      name: Show container logs
      run: |
        docker restart App_v2
        docker-compose logs app
    -
     name: run test with pytest
     run: |
       docker ps
       docker-compose logs db
       pip install --no-cache-dir --upgrade -r requirements.txt
       cd app/
       pip install pytest-html
       python -m pytest --html=../testResults/htmlreport.html --maxfail=3
    - 
      name: Upload test details
      uses: actions/upload-artifact@v2
      with:
        name: ReportTest
        path: ../testResults
