on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: CI/CD
jobs:
  testing-python:
    name: Running tests
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout Repository
      uses: actions/checkout@master
    - 
      name: Running docker container
      run: |
        cd dataDB/Volumen
        mkdir pg_commit_ts pg_dynshmem pg_notify pg_replslot pg_twophase pg_serial pg_snapshots pg_stat pg_stat_tmp pg_tblspc
        cd pg_logical
        mkdir mappings snapshots
        cd ..
        cd pg_wal
        mkdir archive_status
        cd ../../..
        sudo docker-compose up --build -d
    -
      name: Show container logs
      run: |
        docker restart App_v1
        sudo docker ps
        docker-compose logs db
        docker-compose logs app
    -
      name: Requirements
      run: |
        pip list
        pip install -r requirements.txt
    - 
      name: run test with pytest
      run: |
        cd app/
        docker ps
        python -m pytest --html=../testResults/htmlreport.html --maxfail=3
        ls
        cd ..
        ls
    - 
      name: Upload test details
      uses: actions/upload-artifact@v2
      with:
        name: ReportTest
        run: |
        path: ./testResults
