on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: CI/CD
jobs:
  testing-python:
    name: Running tests
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout Repository
      uses: actions/checkout@master
    - 
      name: Running docker container
      run: |
        sudo docker-compose build
        sudo docker-compose up -d
        sudo docker ps
    -
      name: Show container logs
      run: |
        docker restart App_v2
        docker-compose logs app
    -
     name: Enter container
     run: docker exec -t App_v2 /bin/bash
    -
      name: run tests with pytest in container
      run: |
        cd app/
        python -m pytest
