on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: CI/CD
jobs:
  testing-python:
    name: Running tests
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout Repository
      uses: actions/checkout@master
    - 
      name: Running docker container
      run: |
        cd dataDB/Volumen
        mkdir pg_commit_ts
        mkdir pg_dynshmem
        mkdir pg_notify
        mkdir pg_replslot
        mkdir pg_serial
        mkdir pg_snapshots
        mkdir pg_stat
        mkdir pg_stat_tmp
        mkdir pg_tblspc
        mkdir pg_twophase
        cd pg_logical
        mkdir mappings
        mkdir snapshots
        cd ..
        cd pg_wal
        mkdir archive_status
        cd ../../..
        sudo docker-compose build
        sudo docker-compose up -d
    -
      name: Show container logs
      run: |
        sudo docker ps
        docker-compose logs app
        docker-compose logs db
    -
     name: run test with pytest
     run: |
       docker ps
       pip install --no-cache-dir --upgrade -r requirements.txt
       cd app/
       pip install pytest-html
       python -m pytest --html=../testResults/htmlreport.html --maxfail=3
    - 
      name: Upload test details
      uses: actions/upload-artifact@v2
      with:
        name: ReportTest
        path: ../testResults
